language: go
sudo: false
go:
  - "1.10.x"
  - "1.11.x"

before_install:
  - go get -t -v ./...

matrix:
  fast_finish: true
  include:
  - go: 1.11.x
    env: GO111MODULE=on

git:
  depth: 10

go_import_path: github.com/yuexcom/go-xrp

script: 
  - sh run-test.sh
 
after_success:
  - bash <(curl -s https://codecov.io/bash)