sudo: required
language: go
go:
  - "1.11.x"

matrix:
  fast_finish: true
  include:
  - go: 1.11.x
    env: GO111MODULE=on

git:
  depth: 10

go_import_path: github.com/yuexcom/go-xrp

script: 
  - make test
 
after_success:
  - bash <(curl -s https://codecov.io/bash)